title: /dev/blog
email: bezalelhermoso@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My development blog
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://example.com" # the base hostname & protocol for your site
twitter_username: bezhermoso
github_username:  bezhermoso
domain: bezhermoso.github.io
ga_profile: UA-22506121-5

# Build settings
markdown: kramdown

kramdown:
  syntax_highlighter_opts:
    span:
      disable: true

permalink: pretty
excerpt_separator: <!--stop-->

collections:
  til:
    output: true
    permalink: /til/:path/
