title: /dev/blog
email: bezalelhermoso@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My development blog
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://example.com" # the base hostname & protocol for your site
twitter_username: bezhermoso
github_username:  bezhermoso

# Build settings
markdown: kramdown

collections:
  til:
    output: true
    permalink: /til/:path/
