# Site settings
title: The Hunt for the Missing Semicolon
email: bezalelhermoso@gmail.com
description: "Topics that are of particular interest to web developers, especially to Symfony and ZF2 folks."
baseurl: ""
url: "http://bezhermoso.github.io"
twitter_username: BezHermoso
github_username:  bezhermoso

# Build settings
markdown: kramdown
permalink: pretty
